import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer'
import type { ReportInsight } from '@/lib/ai/agent-schemas'

interface ReportWidget {
  id: string
  title: string
}

interface ReportDocumentProps {
  dashboardTitle: string
  insights: ReportInsight
  widgets: ReportWidget[]
}

const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 40,
    paddingHorizontal: 42,
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
    fontSize: 11,
    lineHeight: 1.45,
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    color: '#0F172A',
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 10,
    color: '#64748B',
    marginBottom: 22,
  },
  section: {
    marginBottom: 18,
    padding: 14,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    border: '1 solid #E2E8F0',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: '#1E293B',
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 11,
    color: '#334155',
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  bullet: {
    width: 10,
    fontSize: 11,
    color: '#0F172A',
  },
  bulletText: {
    flex: 1,
    fontSize: 11,
    color: '#334155',
  },
  widgetHeader: {
    marginBottom: 10,
    paddingBottom: 8,
    borderBottom: '1 solid #E2E8F0',
  },
  widgetTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: '#0F172A',
  },
  widgetId: {
    fontSize: 9,
    color: '#64748B',
    marginTop: 2,
  },
  insightCard: {
    marginTop: 8,
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    border: '1 solid #E2E8F0',
  },
  insightLabel: {
    fontSize: 9,
    color: '#475569',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  insightText: {
    fontSize: 11,
    color: '#1E293B',
  },
  emptyText: {
    fontSize: 11,
    color: '#64748B',
  },
  footer: {
    position: 'absolute',
    left: 42,
    right: 42,
    bottom: 20,
    fontSize: 9,
    color: '#94A3B8',
    textAlign: 'center',
  },
})

export function ReportDocument({
  dashboardTitle,
  insights,
  widgets,
}: ReportDocumentProps) {
  const generatedAt = new Date().toLocaleString()
  const anomalies = insights.anomalies ?? []

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{dashboardTitle}</Text>
        <Text style={styles.subtitle}>AI Report - Generated {generatedAt}</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <Text style={styles.summaryText}>{insights.executiveSummary}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Anomalies</Text>
          {anomalies.length > 0 ? (
            anomalies.map((item, index) => (
              <View style={styles.bulletRow} key={`anomaly-${index}`}>
                <Text style={styles.bullet}>-</Text>
                <Text style={styles.bulletText}>{item}</Text>
              </View>
            ))
          ) : (
            <Text style={styles.emptyText}>No significant anomalies detected.</Text>
          )}
        </View>

        <Text style={styles.footer}>Confidential - Generated by AI Dashboard Builder</Text>
      </Page>

      {widgets.map((widget) => (
        <Page key={widget.id} size="A4" style={styles.page}>
          <View style={styles.widgetHeader}>
            <Text style={styles.widgetTitle}>{widget.title}</Text>
            <Text style={styles.widgetId}>Widget ID: {widget.id}</Text>
          </View>

          <View style={styles.insightCard}>
            <Text style={styles.insightLabel}>AI Insight</Text>
            <Text style={styles.insightText}>
              {insights.widgetInsights[widget.id] ?? 'No specific insight was generated for this widget.'}
            </Text>
          </View>

          <Text style={styles.footer}>Confidential - Generated by AI Dashboard Builder</Text>
        </Page>
      ))}
    </Document>
  )
}
