import type { CSSProperties } from 'react'

export type DashboardOsThemeMode = 'dark' | 'light'

export const DASHBOARDOS_THEME_STORAGE_KEY = 'dashboardos-theme-mode'

export const DASHBOARDOS_COLORS = {
  dark: {
    backgroundDeep: '#15171A',
    backgroundBase: '#1D2025',
    surface: '#22272E',
    surfaceRaised: '#2A2D32',
    surfaceMuted: '#383B42',
    textPrimary: '#E6EDF3',
    textSecondary: '#C9D1D9',
    textMuted: '#A7B1BC',
    borderSoft: 'rgba(230, 237, 243, 0.08)',
    borderMid: 'rgba(230, 237, 243, 0.14)',
    cardOverlay: 'rgba(34, 39, 46, 0.72)',
    accentPrimary: '#818CF8',
    accentPrimaryHover: '#A5B4FC',
    accentPrimarySoft: 'rgba(129, 140, 248, 0.12)',
    success: '#34D399',
    successSoft: 'rgba(52, 211, 153, 0.12)',
    warning: '#FBBF24',
    warningSoft: 'rgba(251, 191, 36, 0.12)',
    danger: '#FB7185',
    dangerSoft: 'rgba(251, 113, 133, 0.12)',
    info: '#38BDF8',
    infoSoft: 'rgba(56, 189, 248, 0.12)',
  },
  light: {
    pageBackground: '#F7F8FA',
    surface: '#F0F2F5',
    cardBackground: '#FFFFFF',
    border: '#E5E7EB',
    borderStrong: '#D1D5DB',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#4B5563',
    accentPrimary: '#4F46E5',
    accentPrimaryHover: '#4338CA',
    accentPrimarySoft: 'rgba(79, 70, 229, 0.10)',
    success: '#059669',
    successText: '#064E3B',
    successSoft: 'rgba(5, 150, 105, 0.10)',
    warning: '#D97706',
    warningText: '#78350F',
    warningSoft: 'rgba(217, 119, 6, 0.10)',
    danger: '#E11D48',
    dangerText: '#881337',
    dangerSoft: 'rgba(225, 29, 72, 0.10)',
    info: '#0284C7',
    infoText: '#0C4A6E',
    infoSoft: 'rgba(2, 132, 199, 0.10)',
  },
  chartDefaults: {
    dark: ['#8EA2FF', '#4ADE80', '#FACC15', '#FB7185', '#38BDF8', '#C084FC', '#2DD4BF', '#F472B6'],
    light: ['#4F46E5', '#059669', '#D97706', '#E11D48', '#0284C7', '#9333EA', '#0F766E', '#BE185D'],
  },
  chartSemantic: {
    dark: {
      success: '#4ADE80',
      risk: '#FB7185',
      warning: '#FACC15',
      info: '#38BDF8',
      metadata: '#A7B1BC',
      grid: 'rgba(201, 209, 217, 0.12)',
      axis: '#B8C2CC',
      tooltipBg: 'rgba(21, 23, 26, 0.96)',
      tooltipBorder: 'rgba(142, 162, 255, 0.24)',
    },
    light: {
      success: '#059669',
      risk: '#E11D48',
      warning: '#D97706',
      info: '#0284C7',
      metadata: '#64748B',
      grid: 'rgba(15, 23, 42, 0.10)',
      axis: '#475569',
      tooltipBg: 'rgba(255, 255, 255, 0.98)',
      tooltipBorder: 'rgba(79, 70, 229, 0.18)',
    },
  },
} as const

export function getDashboardOsThemeVars(mode: DashboardOsThemeMode): CSSProperties {
  const dark = DASHBOARDOS_COLORS.dark
  const light = DASHBOARDOS_COLORS.light
  const chartColors = DASHBOARDOS_COLORS.chartDefaults[mode].join(', ')
  const chartSemantic = DASHBOARDOS_COLORS.chartSemantic[mode]

  if (mode === 'light') {
    return {
      '--dos-background-deep': light.pageBackground,
      '--dos-background-base': light.pageBackground,
      '--dos-surface': light.cardBackground,
      '--dos-surface-raised': light.cardBackground,
      '--dos-surface-muted': light.surface,
      '--dos-text-primary': light.textPrimary,
      '--dos-text-secondary': light.textSecondary,
      '--dos-text-muted': light.textMuted,
      '--dos-border-soft': light.border,
      '--dos-border-mid': light.borderStrong,
      '--dos-card-overlay': light.cardBackground,
      '--dos-accent-primary': light.accentPrimary,
      '--dos-accent-primary-hover': light.accentPrimaryHover,
      '--dos-accent-primary-soft': light.accentPrimarySoft,
      '--dos-success': light.success,
      '--dos-success-text': light.successText,
      '--dos-success-soft': light.successSoft,
      '--dos-warning': light.warning,
      '--dos-warning-text': light.warningText,
      '--dos-warning-soft': light.warningSoft,
      '--dos-danger': light.danger,
      '--dos-danger-text': light.dangerText,
      '--dos-danger-soft': light.dangerSoft,
      '--dos-info': light.info,
      '--dos-info-text': light.infoText,
      '--dos-info-soft': light.infoSoft,
      '--dos-chart-defaults': chartColors,
      '--dos-chart-success': chartSemantic.success,
      '--dos-chart-risk': chartSemantic.risk,
      '--dos-chart-warning': chartSemantic.warning,
      '--dos-chart-info': chartSemantic.info,
      '--dos-chart-metadata': chartSemantic.metadata,
      '--dos-chart-grid': chartSemantic.grid,
      '--dos-chart-axis': chartSemantic.axis,
      '--dos-chart-tooltip-bg': chartSemantic.tooltipBg,
      '--dos-chart-tooltip-border': chartSemantic.tooltipBorder,
    } as CSSProperties
  }

  return {
    '--dos-background-deep': dark.backgroundDeep,
    '--dos-background-base': dark.backgroundBase,
    '--dos-surface': dark.surface,
    '--dos-surface-raised': dark.surfaceRaised,
    '--dos-surface-muted': dark.surfaceMuted,
    '--dos-text-primary': dark.textPrimary,
    '--dos-text-secondary': dark.textSecondary,
    '--dos-text-muted': dark.textMuted,
    '--dos-border-soft': dark.borderSoft,
    '--dos-border-mid': dark.borderMid,
    '--dos-card-overlay': dark.cardOverlay,
    '--dos-accent-primary': dark.accentPrimary,
    '--dos-accent-primary-hover': dark.accentPrimaryHover,
    '--dos-accent-primary-soft': dark.accentPrimarySoft,
    '--dos-success': dark.success,
    '--dos-success-text': dark.success,
    '--dos-success-soft': dark.successSoft,
    '--dos-warning': dark.warning,
    '--dos-warning-text': dark.warning,
    '--dos-warning-soft': dark.warningSoft,
    '--dos-danger': dark.danger,
    '--dos-danger-text': dark.danger,
    '--dos-danger-soft': dark.dangerSoft,
    '--dos-info': dark.info,
    '--dos-info-text': dark.info,
    '--dos-info-soft': dark.infoSoft,
    '--dos-chart-defaults': chartColors,
    '--dos-chart-success': chartSemantic.success,
    '--dos-chart-risk': chartSemantic.risk,
    '--dos-chart-warning': chartSemantic.warning,
    '--dos-chart-info': chartSemantic.info,
    '--dos-chart-metadata': chartSemantic.metadata,
    '--dos-chart-grid': chartSemantic.grid,
    '--dos-chart-axis': chartSemantic.axis,
    '--dos-chart-tooltip-bg': chartSemantic.tooltipBg,
    '--dos-chart-tooltip-border': chartSemantic.tooltipBorder,
  } as CSSProperties
}
