import type {
  ChartTemplateDefinition,
  ChartTemplateId,
} from '@/types/chart-template'

export const CHART_TEMPLATE_REGISTRY: ChartTemplateDefinition[] = [
  {
    id: 'kpi-card',
    name: 'KPI Card',
    family: 'summary',
    description: 'Single metric value with optional context fields.',
    requirement: {
      minDimensions: 0,
      maxDimensions: 1,
      minMetrics: 1,
      maxMetrics: 1,
      allowedShapeKinds: ['single_metric', 'name_value'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: false,
    },
    defaultSize: 'compact',
    priority: 72,
  },
  {
    id: 'kpi-grid',
    name: 'KPI Grid',
    family: 'summary',
    description: 'Compact multi-metric summary cards.',
    requirement: {
      minDimensions: 0,
      maxDimensions: 1,
      minMetrics: 2,
      maxMetrics: 6,
      allowedShapeKinds: ['one_dimension_many_metrics', 'wide_table'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: true,
    },
    defaultSize: 'standard',
    priority: 66,
  },
  {
    id: 'bar',
    name: 'Bar Chart',
    family: 'comparison',
    description: 'One category/date dimension compared against one metric.',
    requirement: {
      minDimensions: 1,
      maxDimensions: 1,
      minMetrics: 1,
      maxMetrics: 1,
      allowedShapeKinds: ['name_value', 'time_series'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: true,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: false,
    },
    defaultSize: 'standard',
    priority: 82,
  },
  {
    id: 'horizontal-bar',
    name: 'Horizontal Bar',
    family: 'comparison',
    description: 'Ranked category comparison for long labels or top/bottom lists.',
    requirement: {
      minDimensions: 1,
      maxDimensions: 1,
      minMetrics: 1,
      maxMetrics: 1,
      allowedShapeKinds: ['name_value'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: true,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: false,
    },
    defaultSize: 'standard',
    priority: 80,
  },
  {
    id: 'grouped-bar',
    name: 'Grouped Bar',
    family: 'comparison',
    description: 'One dimension with two to six comparable metric series.',
    requirement: {
      minDimensions: 1,
      maxDimensions: 1,
      minMetrics: 2,
      maxMetrics: 6,
      allowedShapeKinds: ['one_dimension_many_metrics', 'time_series_many_metrics'],
    },
    supports: {
      grouping: true,
      stacking: false,
      drilldown: true,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: true,
    },
    defaultSize: 'wide',
    priority: 88,
  },
  {
    id: 'horizontal-stacked-bar',
    name: 'Horizontal Stacked Bar',
    family: 'composition',
    description: 'One category dimension split into multiple stacked metric bands.',
    requirement: {
      minDimensions: 1,
      maxDimensions: 1,
      minMetrics: 2,
      maxMetrics: 6,
      allowedShapeKinds: ['one_dimension_many_metrics'],
    },
    supports: {
      grouping: false,
      stacking: true,
      drilldown: true,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: true,
    },
    defaultSize: 'wide',
    priority: 86,
  },
  {
    id: 'line',
    name: 'Line Chart',
    family: 'trend',
    description: 'Time-series trend for one metric.',
    requirement: {
      minDimensions: 1,
      maxDimensions: 1,
      minMetrics: 1,
      maxMetrics: 1,
      requiresDateAxis: true,
      allowedShapeKinds: ['time_series'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: false,
    },
    defaultSize: 'wide',
    priority: 84,
  },
  {
    id: 'trend-composed',
    name: 'Trend Composed',
    family: 'trend',
    description: 'Time-series chart mixing multiple values such as count and percent.',
    requirement: {
      minDimensions: 1,
      maxDimensions: 1,
      minMetrics: 2,
      maxMetrics: 4,
      requiresDateAxis: true,
      allowedShapeKinds: ['time_series_many_metrics'],
    },
    supports: {
      grouping: true,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: true,
    },
    defaultSize: 'wide',
    priority: 87,
  },
  {
    id: 'pie',
    name: 'Pie Chart',
    family: 'composition',
    description: 'Small category composition with one metric.',
    requirement: {
      minDimensions: 1,
      maxDimensions: 1,
      minMetrics: 1,
      maxMetrics: 1,
      allowedShapeKinds: ['name_value'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: false,
    },
    defaultSize: 'standard',
    priority: 62,
  },
  {
    id: 'gauge',
    name: 'Gauge',
    family: 'summary',
    description: 'Two-part status comparison or bounded single metric.',
    requirement: {
      minDimensions: 0,
      maxDimensions: 1,
      minMetrics: 1,
      maxMetrics: 2,
      allowedShapeKinds: ['single_metric', 'name_value'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: true,
    },
    defaultSize: 'standard',
    priority: 58,
  },
  {
    id: 'ring-gauge',
    name: 'Ring Gauge',
    family: 'summary',
    description: 'Percent or availability metric with supporting details.',
    requirement: {
      minDimensions: 0,
      maxDimensions: 1,
      minMetrics: 1,
      maxMetrics: 1,
      allowedShapeKinds: ['single_metric', 'name_value'],
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: false,
    },
    defaultSize: 'standard',
    priority: 60,
  },
  {
    id: 'drilldown-bar',
    name: 'Drilldown Bar',
    family: 'drilldown',
    description: 'Parent category chart that can open a lower-level breakdown.',
    requirement: {
      minDimensions: 2,
      maxDimensions: 2,
      minMetrics: 1,
      maxMetrics: 6,
      allowedShapeKinds: ['two_dimensions_one_metric', 'event_list'],
    },
    supports: {
      grouping: true,
      stacking: true,
      drilldown: true,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: true,
    },
    defaultSize: 'wide',
    priority: 74,
  },
  {
    id: 'table-grid',
    name: 'Table Grid',
    family: 'table',
    description: 'Safe fallback for wide, event, and high-cardinality data.',
    requirement: {
      minDimensions: 0,
      maxDimensions: 12,
      minMetrics: 0,
      maxMetrics: 12,
    },
    supports: {
      grouping: false,
      stacking: false,
      drilldown: false,
      customTooltip: true,
      customLabels: true,
      multipleMetrics: true,
    },
    defaultSize: 'full',
    priority: 35,
  },
]

export function getChartTemplate(templateId: ChartTemplateId) {
  return CHART_TEMPLATE_REGISTRY.find(template => template.id === templateId) ?? null
}
