import fs from 'node:fs/promises'
import path from 'node:path'
import JSZip from 'jszip'
import type { DashboardExportConfig } from '@/lib/code-generator/config-builder'
import { generateProjectFromConfig } from '@/lib/code-generator/template-generator'
import { packageProjectAsZip } from '@/lib/code-generator/zip-packager'

const OUTPUT_ROOT = path.resolve('.tmp-export-validation')
const ZIP_PATH = path.join(OUTPUT_ROOT, 'bosch-edition-test.zip')
const EXTRACT_DIR = path.join(OUTPUT_ROOT, 'generated-app')

async function ensureCleanDir(dir: string) {
  await fs.rm(dir, { recursive: true, force: true })
  await fs.mkdir(dir, { recursive: true })
}

function buildValidationConfig(): DashboardExportConfig {
  const chartTypes = [
    'bar',
    'line',
    'area',
    'pie',
    'donut',
    'horizontal-bar',
    'horizontal-stacked-bar',
    'grouped-bar',
    'drilldown-bar',
    'gauge',
    'ring-gauge',
    'status-card',
    'table',
  ] as const

  const endpoints = chartTypes.map((chartType, index) => ({
    id: `endpoint-${index + 1}`,
    name: `${chartType} endpoint`,
    url: `/api/bosch/demo-${index + 1}`,
    method: 'POST',
    authType: 'custom-headers',
  }))

  const widgets = chartTypes.map((chartType, index) => ({
    id: `widget-${index + 1}`,
    title: `${chartType} widget`,
    type: chartType,
    endpointId: endpoints[index].id,
    xAxis: 'label',
    yAxis: 'value',
    colors: ['#E20015', '#007BC0', '#00A651', '#F5A623'],
    barRadius: 5,
    showLegend: true,
    showGrid: true,
  }))

  return {
    meta: {
      id: 'validation-dashboard',
      name: 'Bosch Export Validation',
      description: 'Generated for Sprint 4 ZIP validation',
      exportedAt: new Date().toISOString(),
    },
    projectConfig: {
      dashboardId: 'validation-dashboard',
      clientName: 'Bosch / UPPCL',
      projectTitle: 'Bosch UPPCL Validation',
      baseUrl: '/api/bosch',
      chartTheme: 'bosch-uppcl',
      layout: 'sidebar',
      authStrategy: 'none',
      defaultHeaders: {
        userid: '{{BOSCH_USERID}}',
        password: '{{BOSCH_PASSWORD}}',
      },
      header: {
        projectName: 'Bosch UPPCL Validation',
        subtitle: 'Generated by Sprint 4 validation',
        primaryColor: '#2C3E50',
        accentColor: '#E20015',
        navDensity: 'comfortable',
      },
      login: {
        endpoint: '/userLogin',
        usernameField: 'username',
        passwordField: 'password',
        tokenPath: 'data.token',
        encodingType: 'plain',
      },
      session: {
        logoutOn401: true,
        logoutOnMessage: 'expired',
      },
    },
    endpoints,
    widgets,
    groups: [],
  }
}

async function writeZip(blob: Blob) {
  const buffer = Buffer.from(await blob.arrayBuffer())
  await fs.writeFile(ZIP_PATH, buffer)
}

async function extractZip(zipPath: string, outputDir: string) {
  const raw = await fs.readFile(zipPath)
  const zip = await JSZip.loadAsync(raw)

  await Promise.all(
    Object.values(zip.files).map(async (entry) => {
      const destination = path.join(outputDir, entry.name)
      if (entry.dir) {
        await fs.mkdir(destination, { recursive: true })
        return
      }
      await fs.mkdir(path.dirname(destination), { recursive: true })
      const content = await entry.async('nodebuffer')
      await fs.writeFile(destination, content)
    }),
  )
}

async function main() {
  await ensureCleanDir(OUTPUT_ROOT)
  await ensureCleanDir(EXTRACT_DIR)

  const config = buildValidationConfig()
  const files = generateProjectFromConfig(config)
  const zipBlob = await packageProjectAsZip(files)

  await writeZip(zipBlob)
  await extractZip(ZIP_PATH, EXTRACT_DIR)

  process.stdout.write(`${ZIP_PATH}\n${EXTRACT_DIR}\n`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
