import type { DashboardExportConfig } from './config-builder'

export type GeneratedFileMap = Record<string, string>

export function generateProjectFromConfig(config: DashboardExportConfig): GeneratedFileMap {
  const files: GeneratedFileMap = {}

  files['package.json'] = JSON.stringify(
    {
      name: slugify(config.meta.name),
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
      },
      dependencies: {
        next: '^14.0.0',
        react: '^18.0.0',
        'react-dom': '^18.0.0',
        recharts: '^2.10.0',
      },
      devDependencies: {
        typescript: '^5.0.0',
        '@types/node': '^20.0.0',
        '@types/react': '^18.0.0',
        '@types/react-dom': '^18.0.0',
      },
    },
    null,
    2
  )

  files['next.config.mjs'] = `/** @type {import('next').NextConfig} */
const nextConfig = {}
export default nextConfig
`

  files['tsconfig.json'] = JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: false,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    },
    null,
    2
  )

  files['src/app/layout.tsx'] = `import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '${config.meta.name}',
  description: '${config.meta.description ?? 'Exported dashboard'}',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: 'system-ui, sans-serif', background: '#f8f9fa' }}>
        {children}
      </body>
    </html>
  )
}
`

  files['src/app/page.tsx'] = `import { dashboardConfig } from '@/lib/config'
import { WidgetChart } from '@/components/WidgetChart'

export default function DashboardPage() {
  return (
    <main style={{ padding: '2rem', maxWidth: '1400px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '1.75rem', fontWeight: 700, marginBottom: '0.25rem', color: '#111827' }}>
        {dashboardConfig.meta.name}
      </h1>
      {dashboardConfig.meta.description && (
        <p style={{ color: '#6b7280', marginBottom: '2rem', marginTop: '0.25rem' }}>
          {dashboardConfig.meta.description}
        </p>
      )}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(480px, 1fr))',
          gap: '1.5rem',
        }}
      >
        {dashboardConfig.widgets.map((widget) => (
          <WidgetChart key={widget.id} widget={widget} endpoints={dashboardConfig.endpoints} />
        ))}
      </div>
    </main>
  )
}
`

  files['src/lib/config.ts'] = `// Auto-generated by Analytics AI Dashboard Builder
// Exported on: ${new Date(config.meta.exportedAt).toLocaleString()}
export const dashboardConfig = ${JSON.stringify(config, null, 2)} as const
`

  files['src/components/WidgetChart.tsx'] = buildWidgetChartComponent()

  files['README.md'] = `# ${config.meta.name}

> Exported from **Analytics AI Dashboard Builder** on ${new Date(config.meta.exportedAt).toLocaleDateString()}.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to view your dashboard.

---

## Widgets (${config.widgets.length})

${config.widgets.map((w) => `- **${w.title}** — \`${w.type}\` chart · X: \`${w.xAxis}\` · Y: \`${w.yAxis}\``).join('\n')}

## Endpoints (${config.endpoints.length})

${config.endpoints.map((e) => `- **${e.name}**: \`${e.method} ${e.url}\``).join('\n')}
`

  return files
}

// ─── helpers ───────────────────────────────────────────────────────────────

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'dashboard'
}

function buildWidgetChartComponent(): string {
  return `'use client'

import { useEffect, useState } from 'react'
import {
  LineChart, BarChart, AreaChart, PieChart,
  Line, Bar, Area, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
} from 'recharts'

const COLORS = ['#6366f1', '#8b5cf6', '#ec4899', '#f59e0b', '#10b981', '#3b82f6', '#ef4444']

interface WidgetConfig {
  id: string
  title: string
  type: string
  endpointId: string
  xAxis: string
  yAxis: string
}

interface EndpointConfig {
  id: string
  name: string
  url: string
  method: string
}

interface Props {
  widget: WidgetConfig
  endpoints: EndpointConfig[]
}

export function WidgetChart({ widget, endpoints }: Props) {
  const [data, setData] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const endpoint = endpoints.find((e) => e.id === widget.endpointId)
    if (!endpoint) {
      setError('Endpoint not found')
      setLoading(false)
      return
    }

    fetch(endpoint.url, { method: endpoint.method })
      .then((r) => {
        if (!r.ok) throw new Error(\`HTTP \${r.status}\`)
        return r.json()
      })
      .then((json) => {
        const arr = Array.isArray(json)
          ? json
          : json.data || json.results || json.items || [json]
        setData(arr)
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [widget.endpointId, widget.xAxis, widget.yAxis])

  const cardStyle: React.CSSProperties = {
    background: '#ffffff',
    border: '1px solid #e5e7eb',
    borderRadius: '12px',
    padding: '1.25rem',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  }

  const titleStyle: React.CSSProperties = {
    fontSize: '0.9rem',
    fontWeight: 600,
    marginBottom: '1rem',
    color: '#111827',
  }

  if (loading) {
    return (
      <div style={{ ...cardStyle, display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 220 }}>
        <p style={{ color: '#9ca3af', fontSize: '0.85rem' }}>Loading…</p>
      </div>
    )
  }

  if (error) {
    return (
      <div style={{ ...cardStyle, minHeight: 220 }}>
        <p style={titleStyle}>{widget.title}</p>
        <p style={{ color: '#ef4444', fontSize: '0.8rem' }}>Error: {error}</p>
      </div>
    )
  }

  const renderChart = () => {
    switch (widget.type) {
      case 'line':
        return (
          <LineChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis dataKey={widget.xAxis} tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} />
            <Tooltip />
            <Legend />
            <Line type="monotone" dataKey={widget.yAxis} stroke="#6366f1" strokeWidth={2} dot={false} />
          </LineChart>
        )
      case 'area':
        return (
          <AreaChart data={data}>
            <defs>
              <linearGradient id="grad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor="#6366f1" stopOpacity={0.3} />
                <stop offset="95%" stopColor="#6366f1" stopOpacity={0} />
              </linearGradient>
            </defs>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis dataKey={widget.xAxis} tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} />
            <Tooltip />
            <Legend />
            <Area type="monotone" dataKey={widget.yAxis} stroke="#6366f1" fill="url(#grad)" strokeWidth={2} />
          </AreaChart>
        )
      case 'bar':
        return (
          <BarChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis dataKey={widget.xAxis} tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} />
            <Tooltip />
            <Legend />
            <Bar dataKey={widget.yAxis} fill="#6366f1" radius={[4, 4, 0, 0]} />
          </BarChart>
        )
      case 'pie':
        return (
          <PieChart>
            <Pie
              data={data}
              dataKey={widget.yAxis}
              nameKey={widget.xAxis}
              cx="50%"
              cy="50%"
              outerRadius={90}
              label
            >
              {data.map((_, index) => (
                <Cell key={index} fill={COLORS[index % COLORS.length]} />
              ))}
            </Pie>
            <Tooltip />
            <Legend />
          </PieChart>
        )
      case 'table':
        return (
          <div style={{ overflowX: 'auto', maxHeight: 260, overflowY: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.78rem' }}>
              <thead>
                <tr>
                  {Object.keys(data[0] || {}).map((col) => (
                    <th
                      key={col}
                      style={{
                        padding: '6px 10px',
                        background: '#f9fafb',
                        borderBottom: '1px solid #e5e7eb',
                        textAlign: 'left',
                        color: '#6b7280',
                        fontWeight: 600,
                        whiteSpace: 'nowrap',
                      }}
                    >
                      {col}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {data.map((row, i) => (
                  <tr key={i} style={{ borderBottom: '1px solid #f3f4f6' }}>
                    {Object.values(row).map((val, j) => (
                      <td key={j} style={{ padding: '6px 10px', color: '#374151' }}>
                        {String(val)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )
      default:
        return <p style={{ color: '#9ca3af' }}>Unknown chart type: {widget.type}</p>
    }
  }

  return (
    <div style={cardStyle}>
      <p style={titleStyle}>{widget.title}</p>
      <ResponsiveContainer width="100%" height={240}>
        {renderChart() as React.ReactElement}
      </ResponsiveContainer>
    </div>
  )
}
`
}
